spring:

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show_sql: true
  datasource:
    url: "jdbc:mysql://host.docker.internal:3306/pojectdb"
    username: root
    password: 159753